[source.cargo]
directory = '/home/christian/ports/cosmic-session/work/cosmic-session-epoch-1.0.0-beta.7/cargo-crates'
[source.crates-io]
replace-with = 'cargo'
[patch.'https://github.com/pop-os/dbus-settings-bindings']
cosmic-dbus-a11y = { path = '/home/christian/ports/cosmic-session/work/dbus-settings-bindings-3b86984332be2c930a3536ab714b843c851fa8ca/a11y' }
[patch.'https://github.com/pop-os/cosmic-notifications']
cosmic-notifications-util = { path = '/home/christian/ports/cosmic-session/work/cosmic-notifications-744439a6e79f7bcb74ba861d525318f9b774c7f5/cosmic-notifications-util' }
[patch.'https://github.com/pop-os/launch-pad']
launch-pad = { path = '/home/christian/ports/cosmic-session/work/launch-pad-5e8e72a676337cad3335f4b46b09f12c41e208ae' }
